package de.fruxz.sparkle.framework.infrastructure.command.structured

import de.fruxz.sparkle.framework.extension.interchange.InterchangeExecutor
import de.fruxz.sparkle.framework.infrastructure.command.Interchange
import de.fruxz.sparkle.framework.infrastructure.command.InterchangeResult
import de.fruxz.sparkle.framework.infrastructure.command.InterchangeUserRestriction.ONLY_CONSOLE
import de.fruxz.sparkle.framework.infrastructure.command.completion.InterchangeStructure
import de.fruxz.sparkle.framework.infrastructure.command.live.InterchangeAccess
import de.fruxz.sparkle.framework.infrastructure.command.live.InterchangeReaction
import de.fruxz.sparkle.framework.permission.Approval
import net.kyori.adventure.text.Component
import org.bukkit.command.ConsoleCommandSender
import kotlin.coroutines.CoroutineContext
import kotlin.time.Duration

abstract class StructuredConsoleInterchange(
	label: String,
	val structure: InterchangeStructure<ConsoleCommandSender>,
	aliases: Set<String> = emptySet(),
	protectedAccess: Boolean = true,
	ignoreInputValidation: Boolean = false,
	description: String = "An command, generated by sparkle!",
	permissionMessage: Component? = null,
	cooldown: Duration = Duration.ZERO,
	forcedWrongUsageReaction: InterchangeReaction? = null,
	forcedApproval: Approval? = null,
	forcedExecutionContext: CoroutineContext? = null,
) : Interchange(
	label = label,
	aliases = aliases,
	requiresApproval = protectedAccess,
	requiredClient = ONLY_CONSOLE,
	completion = structure,
	ignoreInputValidation = ignoreInputValidation,
	description = description,
	permissionMessage = permissionMessage,
	cooldown = cooldown,
	forcedWrongUsageReaction = forcedWrongUsageReaction,
	forcedApproval = forcedApproval,
	forcedExecutionContext = forcedExecutionContext,
) {

	final override val execution: suspend InterchangeAccess<out InterchangeExecutor>.() -> InterchangeResult = {
		structure.performExecution(this)
	}

}